# This is a basic workflow to help you get started with Actions
name: CI
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  say_hello:
    runs-on: ubuntu-latest
      steps:
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            known_hosts:  ${{ secrets.SSH_HOST }}
          run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          run: rsync -avz ./Projet-annuel-Predfackers/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/
