# This is a basic workflow to help you get started with Actions
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: CI
steps:
  - name: Install SSH Key
    uses: shimataro/ssh-key-action@v2
    with:
      key: ${{ secrets.SSH_PRIVATE_KEY }}
      known_hosts:  ${{ secrets.SSH_HOST }}
  - name: Adding Known Hosts
    run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
  - name: Deploy with rsync
    run: rsync -avz ./Projet-annuel-Predfackers/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/
